### ISSUE TITLE
Content Selector - Selected items disappear after drag'n'drop 

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#101]
1. Create a new content that has a Content Selector, but don't save it.
2. Select some items in the dropdown
3. Try to drag around one of the items in the list - works fine
4. Now save the content
5. Try to DnD again. This time, when you drop the item the entire list disappears.

Seems to happen because `getMissingOptionsIds` in `ComboBox` class fails to find selected options by id.

**Comment by vbradnitski** [comment]
Should be merged after #94
