### ISSUE TITLE
Incorrect overflow behaviour inside modal dialog after resize

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#1078]
@sgauruseu commented on [Wed Aug 21 2019](https://github.com/enonic/app-contentstudio/issues/823)

1. Select a content and open  Publishing Wizard.
2. Click on add schedule icon then  click on the icon and open picker popup,
**BUG:**
![image](https://user-images.githubusercontent.com/3728712/63418943-9631ab80-c40c-11e9-87f4-bb7e2e813dc5.png)

**Comment by sgauruseu** [comment]
![image](https://user-images.githubusercontent.com/3728712/64029476-5164ed80-cb4d-11e9-9c25-f8ec36871f65.png)

Probably I have found one more case for this issue

**Comment by sgauruseu** [comment]
new issue is opened for the last case : https://github.com/enonic/lib-admin-ui/issues/1085
