### ISSUE TITLE
HTML Area - Alt-Shift-Tab must move focus to previous field in the form

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#109]
In the form Tab moves focus to the next field and Shift-Tab moves focus to the previous field.

In HTML Area we cannot use Tab and Shift-Tab (they are used internally for indentation).  So we should use Alt-Tab for the next field and Alt-Shift-Tab for previous (now both of them focus the next field).

**Comment by pmi** [comment]
@alansemenov Alt is not the best option because alt + tab is used to cycle apps in windows, similarly alt + shift + tab cycles them counterclockwise. 
Also how is user supposed to know what combination should be used for the text area ?

**Comment by alansemenov** [comment]
We will document the keyboard shortcuts, it's not a problem.

But good catch about the Win conflict. We may have to support two different pairs of shortcuts then, one for Mac and one for Win. What about Cmd+Tab and Cmd+Shift+Tab on Win?

**Comment by pmi** [comment]
Bad luck again - used in chrome to cycle tabs :(

**Comment by alansemenov** [comment]
Ok, let's for now support these only under Mac - it's better than nothing
