### ISSUE TITLE
Translate missing phrases to Portuguese

### ISSUE THREAD

**Issue by jsi** [enonic/lib-admin-ui#1101]
The following phrases are missing Portuguese translations:
 - dialog.notification.title
 - field.dateTimeRange.errors.endBeforeStart
 - field.dateTimeRange.errors.endInPast
 - field.dateTimeRange.errors.noStart
 - field.selection.clear
 - field.selection.selectAll
 - notify.optionset.notempty
 - status.expired
 - status.pending
 - status.workflow.in_progress
 - status.workflow.ready

This is the file for the translations: https://github.com/enonic/lib-admin-ui/blob/master/src/main/resources/i18n/common_pt.properties

**Comment by bzmelotti** [comment]
- dialog.notification.title = Notificação
- field.dateTimeRange.errors.endBeforeStart = A data final deve ser maior do que a data de inicio
- field.dateTimeRange.errors.endInPast = A data final não pode ser no passado
- field.dateTimeRange.errors.noStart = A data final não poder definida antes da data de inicio
- field.selection.clear = Limpar seleção
- field.selection.selectAll = Selecionar todas as linhas
- notify.optionset.notempty = Os campos desmarcados serão limpos ao salvar
- status.expired = Expirado
- status.pending = Pendente
- status.workflow.in_progress = Progresso
- status.workflow.ready = Proto para ser publicado
