### ISSUE TITLE
Translate missing phrases to Spanish

### ISSUE THREAD

**Issue by jsi** [enonic/lib-admin-ui#1102]
The following phrases are missing Spanish translations:
 - dialog.notification.title
 - field.dateTimeRange.errors.endBeforeStart
 - field.dateTimeRange.errors.endInPast
 - field.dateTimeRange.errors.noStart
 - field.selection.clear
 - field.selection.selectAll
 - notify.optionset.notempty
 - status.expired
 - status.pending
 - status.workflow.in_progress
 - status.workflow.ready

**Comment by Blask0** [comment]
In which file? @jsi

**Comment by Blask0** [comment]
https://github.com/enonic/lib-admin-ui/pull/1177 done, have a look.
