### ISSUE TITLE
Translate missing phrases to Swedish

### ISSUE THREAD

**Issue by jsi** [enonic/lib-admin-ui#1103]
The following phrases are missing Swedish translations:
 - dialog.notification.title
 - field.dateTimeRange.errors.endBeforeStart
 - field.dateTimeRange.errors.endInPast
 - field.dateTimeRange.errors.noStart
 - field.selection.clear
 - field.selection.selectAll
 - notify.optionset.notempty
 - status.expired
 - status.pending
 - status.workflow.in_progress
 - status.workflow.ready

**Comment by Bellfalasch** [comment]
In progress, todo:
notify.optionset.notempty
status.expired
status.pending
status.workflow.in_progress
status.workflow.ready

**Comment by Bellfalasch** [comment]
Done
