### ISSUE TITLE
Selection filter doesn't work after clicking on refresh icon

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1222]
**Case 1**

1. Expand a folder, select two items
2. Click on `Show Selection` circle

![image](https://user-images.githubusercontent.com/3728712/77526362-7c24e380-6e9b-11ea-832f-56472a24ab83.png)

3. Click on refresh icon
![image](https://user-images.githubusercontent.com/3728712/77526538-d1f98b80-6e9b-11ea-956d-d8eb0f19bb3a.png)

**Bug - Selection checkbox gets not clickable after refreshing the grid**

**Case 2**
Click on the checkbox and select all:

![image](https://user-images.githubusercontent.com/3728712/77634597-4860c100-6f62-11ea-98a2-fd3b1485b119.png)

- Click on refresh icon.  Bug - SelectionPanelToggler gets not visible:

![image](https://user-images.githubusercontent.com/3728712/77634661-5f071800-6f62-11ea-92fb-5871a39dc1aa.png)

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/lib-admin-ui/pull/1235
