### ISSUE TITLE
Set visibility of Tree Context Menu item based on underlying action

### ISSUE THREAD

**Issue by pmi** [enonic/lib-admin-ui#126]
@sgauruseu commented on [Tue Aug 01 2017](https://github.com/enonic/xp/issues/5393)

1. start to add a new page-template in the Features.
2. select a page controller .
3. open the Page Component View and show the context menu.
4. select  'Save as Template'.

BUG: 'Save as Template' should be hidden
![templ](https://user-images.githubusercontent.com/3728712/28830250-e3a8574c-76de-11e7-90ee-022793414f1a.png)

**Comment by alansemenov** [comment]
@pmi this was most likely caused by the fix of https://github.com/enonic/lib-admin-ui/issues/122. please verify that the context menu is still correct after your fix of this one.
