### ISSUE TITLE
Incorrect behavior of 'Show selection'  when a single content is highlighted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1266]
1. Click on row with 'Large Tree'
2. Click on checkbox in this highlighted row 
3. `Show selection` button appears (OK)
![image](https://user-images.githubusercontent.com/3728712/80585412-f35e1200-8a1b-11ea-81b5-a66f4d848d9c.png)

4. Click on `Show selection`:
![image](https://user-images.githubusercontent.com/3728712/80585674-6b2c3c80-8a1c-11ea-9e51-c032a64c1c49.png)

**BUG**:  Grid is not filtered after clicking on   `Show selection`, the row gets unchecked.

**Expected behavior:** 
![image](https://user-images.githubusercontent.com/3728712/80585482-15579480-8a1c-11ea-8a5f-31a67bd044ea.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/pull/1275
