### ISSUE TITLE
Implement image preview in Image Selector in mobile resolution

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#130]
In mobile mode a click on the image thumbnail inside the Image Selector should open the fullscreen overlay with image preview.

At the bottom of the overlay there will be two buttons: Select (blue) and Close (grey).
A click on Select should close the overlay and select that image inside the selector (check off the checkbox). If the selector is multi-choice then nothing else should happen. If the selector is single-choice then the selection should be applied (the image should be added to the selected options) and the dropdown will close.
A click on Close should close the overlay but not the selector's dropdown.

If the image is too high, there should be a vertical scrollbar but the button toolbar should be docked to the bottom.

![image](https://user-images.githubusercontent.com/11612490/31944727-5a38c812-b8cd-11e7-8814-e420c805f3fc.png)

**Comment by sigdestad** [comment]
I Guess the button should be blue and state "Select"?

**Comment by alansemenov** [comment]
👍  for the blue button and Select, but then we should change "Apply" to "Select" inside the selector too? Although the two buttons are doing slightly different things, so maybe it's ok to have two different buttons.

**Comment by sigdestad** [comment]
Don't agree, as select means (check box) where apply means close the selector and update all selections. So I think the current solution is fine...
