### ISSUE TITLE
Double clicking does not open item in filtered grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1339]
Case 1:  do double click on the filtered project:

![image](https://user-images.githubusercontent.com/3728712/84513307-ec404a00-acd1-11ea-90dc-840cfd200b86.png)

Case 2:   do double click on the filtered site: 

![image](https://user-images.githubusercontent.com/3728712/84513444-18f46180-acd2-11ea-9278-c89cd65205a1.png)

Expected : Item should be opened.
Actual:   Projects folder gets highlighted: 

![image](https://user-images.githubusercontent.com/3728712/84513549-43deb580-acd2-11ea-8b5b-30c7a16327d3.png)

**Comment by ashklianko** [comment]
Tricky issue: click handler is being invoked immediately since we want to select grid items as fast as possible, so double click handler is invoked after single click handler
