### ISSUE TITLE
Missing warnings in Content Studio in read-only mode for duplication and sorting

### ISSUE THREAD

**Issue by RF0** [enonic/lib-admin-ui#134]
When setting the cms-repo in read-only mode with "./toolbox.sh set-read-only -a su:password -b -r cms-repo true" ; I get no error / warning message when 

1. Trying to duplicate a selected content
2. Trying to change sort order of a content (spinning wheel of death)

Enonic XP 6.12.1
Chrome

**Comment by sigdestad** [comment]
We will solve this by making available a message in the footer just like we do with with offline. The popup must appear automatically and disappear when read only is turned off again. Just like offline red stripe.

**Comment by alansemenov** [comment]
Created a new epic here: https://github.com/enonic/xp/issues/5832
