### ISSUE TITLE
Enable discarding new unsaved content

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#138]
@alansemenov commented on [Tue Oct 24 2017](https://github.com/enonic/xp-apps/issues/181)

When user creates a new content, we always create it in the repo and it will stay there even if user closes the Wizard tab without ever saving it (as "unnamed"). 
There's an option to use "Delete" button in the toolbar but it's not very obvious why you should Delete a content you have never saved. Also, for a new site it's even worse because there you will get a confirmation dialog to delete the site itself and its Template folder.

What we should do is show confirmation dialog when user closes Wizard tab for a new content **he never saved** that will look like this (like SaveBeforeClose in the Users app):

![image](https://user-images.githubusercontent.com/11612490/31986379-8a70f5e0-b968-11e7-9b7d-f0cf9731a8d5.png)

Remember to add localisation for the button captions and the dialog message.

Pressing "Keep" will save the changes (if there were any) and close the tab. Pressing "Discard" will delete the content (without any additional confirmations, like the one described above). 

Important:
- The native browser's confirmation dialog should not be shown in the case when we show the dialog about discarding the new content
- If the new content was saved and then changed, then closing the tab should show the native confirmation. The new one should only be shown for unsaved content.
- If the new content was opened from the grid (not from the New Content dialog) then the new dialog should not be used even if the content was never saved 
- "Delete" action in the toolbar should be hidden for new content until it's saved for the first time 

---

@sigdestad commented on [Tue Oct 24 2017](https://github.com/enonic/xp-apps/issues/181#issuecomment-339050175)

Great! But can we change the buttons to "Keep" and "Delete" instead of "yes" and "no"?

---

@edloidas commented on [Tue Oct 24 2017](https://github.com/enonic/xp-apps/issues/181#issuecomment-339114086)

I can totally agree, that we need modal dialogs, that has simple text and buttons with clear meaning, so that user can read only the labels and understand what that button will do, without reading the question.

---

@alansemenov commented on [Wed Oct 25 2017](https://github.com/enonic/xp-apps/issues/181#issuecomment-339240766)

Sure

**Comment by sigdestad** [comment]
I like the _K and _D - guess it implies keyboard shortcuts. Do we use that already today in the system?

**Comment by alansemenov** [comment]
We do, but it's hardcoded in each modal dialog, usually to "Y" and "N" for Yes and No. We need to implement a solution where localisation is taken into account.

**Comment by sigdestad** [comment]
I see, let's put that in the back-log and not do it now...
