### ISSUE TITLE
New occurrence won't fire edit content events

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1416]
When a new occurrence of a composite input (like an item-set or an option-set) is added, which has in it another input like an image selector or a content selector, then edit button/icon will not work for selected content in these selectors. After the content is saved, edit button/icon starts working as it should.

https://discuss.enonic.com/t/edit-button-is-not-working-on-imageselector-in-an-item-set/2280/2

**Comment by bzmelotti** [comment]
@alansemenov , do you know if this bug fix has been pushed to the 7.6.0 version?

**Comment by alansemenov** [comment]
@bzmelotti all of the fixes made before the release of 7.6.0 should be in that release, yes
