### ISSUE TITLE
Show image display name and path in gallery mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#144]
Show display name at the bottom of each image (as shown in the screenshot).
Show path inside a tooltip (on image hover).

![image](https://user-images.githubusercontent.com/11612490/32267535-e0b9679c-beeb-11e7-8bd2-1fece49b171e.png)

**Comment by alansemenov** [comment]
Name is there now but there's no tooltip with path

**Comment by pmi** [comment]
Right, overlooked that part :( 
Should be there now !
