### ISSUE TITLE
Browse Panel -  grid is not refreshed after adding items  in the filtered grid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1475]
@sgauruseu commented on [Mon Sep 21 2020](https://github.com/enonic/app-contentstudio/issues/2311)

1. Add child layer in Default project.
2. Select the layer - click on on the checkbox.
3. Click on Show Selections
4. Add new layer in the filtered grid.

BUG: 
1) new layer is not displayed in the filtered grid
![image](https://user-images.githubusercontent.com/3728712/93784349-97e42900-fc35-11ea-933e-c32300c04c20.png)

2) Clear the selections, new layer is not present in this grid as well 

![image](https://user-images.githubusercontent.com/3728712/93784420-ac282600-fc35-11ea-9b81-84598a4b17cf.png)

Click on Refresh icon - new layer appears:  
![image](https://user-images.githubusercontent.com/3728712/93784468-ba764200-fc35-11ea-8f65-c97945b550cc.png)

**Comment by ashklianko** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/pull/1516

**Comment by ashklianko** [comment]
@sgauruseu please also recheck this now

**Comment by sgauruseu** [comment]
I verified it in master
