### ISSUE TITLE
Don't auto-expand item/option-sets in existing content

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1497]
When a new occurrence of an item-set is added, we auto-expand the item-set and that is fine. However, when we open Content Wizard for an existing content we should collapse all item/option-sets by default. The reason is that some content types contain lots of complex sets while user typically needs to change just one (or none), so expanding all of the sets at once makes the form too complex to search through.

Fix this in FormSetOccurrenceView so that this logic is common for item- and option-sets.

**Comment by sigdestad** [comment]
It will be a happy day when this is solved :-)
