### ISSUE TITLE
Notify about deleted content if it was opened from the Content Grid and then deleted

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#156]
1. Open a content wizard, type data and save the content
2. Do not close the wizard and click on Delete button and confirm it 

Expected: contend is deleted, wizard closed and  required 'notification message ' should appears in the browse panel

**Comment by alansemenov** [comment]
It's a tricky one since the window that is supposed to initiate the message is already closed. So it may not even be doable. We should research whether it's possible to give a message in the Content grid window upon receiving a server event notification about deletion, but only if that is the same window from where the Wizard was opened.

**Comment by alansemenov** [comment]
We will not do this. Implementing this will mean giving notifications in the grid window about every deleted content and we don't want that. And there's no easy way to give notifications only for the deleted content that was opened from the same window.

**Comment by sigdestad** [comment]
What do you mean "required notification" should appear in browse panel? I thougt the content should simply be removed from the browse view, without any notifications?

**Comment by alansemenov** [comment]
Yes, that's how it is now. What he meant is that we should show a notification about a content deleted from the wizard tab similar to how we notify when deleting a content directly from the grid.

**Comment by sigdestad** [comment]
Ok. I disagree with that approach. It will be more than sufficient for the user to close the window he actually deleted the content in.

**Comment by alansemenov** [comment]
That's why I wrote that we won't do it and closed the issue?
