### ISSUE TITLE
Long labels for an option within a option-set breaks the layout

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-admin-ui#1565]
If you add long labels for an `option` within a `option-set` the blue background will turn into a border, more like when wrapping multiple items within.

Here's an example of two long labels. Without any selected it looks ok but not perfect, but when selecting it if the text doesn't fit the size of the component config area it will switch to a different layout/look instead of just being a background. Could this be improved? It would be nice if we also could see the entire label for selected items, even if they're long.

On a small screen:

<img width="471" alt="Skjermbilde 2020-11-11 kl  08 32 56" src="https://user-images.githubusercontent.com/1465598/98790680-5e919380-2404-11eb-81c7-948e3593b0c9.png">

Looks better when making right side bigger:

<img width="723" alt="Skjermbilde 2020-11-11 kl  08 32 42" src="https://user-images.githubusercontent.com/1465598/98790676-5df8fd00-2404-11eb-87d6-a03c84983e18.png">

We bypassed this for now by using help-text for additional information, but it would be nice to not break like this.

**Comment by Bellfalasch** [comment]
Or worse when right-side menu opens in default size. Even the un-selected label breaks in an ugly way.

<img width="271" alt="Skjermbilde 2020-11-11 kl  11 31 34" src="https://user-images.githubusercontent.com/1465598/98801115-9eab4300-2411-11eb-87ea-f860db84030b.png">

**Comment by sigdestad** [comment]
FYI: Issue might be fixed with the new and improved optionset design
