### ISSUE TITLE
Implement common label for all set occurrences

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1611]
NB! This should be done both for item- and option-sets.

For regular input types, like text line for example, we show input type label once above all the occurrences:

![image](https://user-images.githubusercontent.com/11612490/100848227-215b7700-3481-11eb-8f30-02ef6591358d.png)

For option and item-sets however we repeat the label in each occurrence's header:

![image](https://user-images.githubusercontent.com/11612490/100850005-78fae200-3483-11eb-8a2f-3e0a403162a1.png)

Implement one common label above `occurrence-views-container`, using the same styling as we use for a FieldSet's label:

![image](https://user-images.githubusercontent.com/11612490/100849590-10ac0080-3483-11eb-95c2-48b1b55d5218.png)

For now, keep the label in occurrence's header as well.

**Comment by pmi** [comment]
Done in https://github.com/enonic/lib-admin-ui/issues/1619
