### ISSUE TITLE
Enable inserting a new occurrence in specified index

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1616]
NB! This should be done both for item- and option-sets.

"`Add <input label>`" button in the `bottom-button-row` adds a new occurrence to the bottom of the occurrence view container. By implementing for each occurrence a [new context menu](https://github.com/enonic/lib-admin-ui/issues/1615) with items "_Add above_" and "_Add below_" we will enable adding a new occurrence before or after a specific occurrence.

**Comment by pmi** [comment]
Done in lib-admin-ui/1615
