### ISSUE TITLE
Cache response of IsAuthenticatedRequest

### ISSUE THREAD

**Issue by ashklianko** [enonic/lib-admin-ui#1648]
IsAuthenticatedRequest will return same auth data no matter if there were updates on user or not. Auth data  is stored in session and won't change until you logout and login again. So maybe it is time we stop sending requests each time and use cached data in request? Or use some AuthenticationContext to be init on login and providing login result data in a static way? @alansemenov what you think?

**Comment by alansemenov** [comment]
Good idea, let's do this after 3.2 release.
