### ISSUE TITLE
Filtering of options with white spaces is not working in OptionSet

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1700]
**Case 1**
1. Select Features, open new Option Set wizard
2. Type `Option` in Single selection option filter input

![image](https://user-images.githubusercontent.com/3728712/104184060-ee16eb00-5423-11eb-92fd-8a011397e954.png)
  Two options are available - OK

3. Change text to `Option 1`

**BUG :**  The filtering does not work when text with white spaces has ben typed in the input

![image](https://user-images.githubusercontent.com/3728712/104184269-3c2bee80-5424-11eb-8091-0ae1f8edf69b.png)

**Case 2**

1. Add one more option in the dropdown in Single selection 
```
<option name="option_3">
          <label>myoption</label>
          <help-text>Help text for Option 3</help-text>
        </option>
```
2. Type `myoption` in the filter input
BUG - required  option is not filtered

![image](https://user-images.githubusercontent.com/3728712/104430775-2fc8a280-5598-11eb-9179-86d2a8e26a96.png)

But actually  this option is present the dropdown list

![image](https://user-images.githubusercontent.com/3728712/104430953-67cfe580-5598-11eb-9f60-88b82afe705c.png)

**Comment by alansemenov** [comment]
Has to be fixed in a different way
