### ISSUE TITLE
Incorrect handling of Enter key event in dropdown in OptionSet

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1707]
1. Select Features  and open new Option Set wizard, 
2. type a name of not existing content  and press Enter key.

![image](https://user-images.githubusercontent.com/3728712/104449040-0c5d2200-55af-11eb-8aa5-b5cf9232184f.png)

3. click outside the selector, the selector is closed - OK
4. Click on the dropdown handle of this selector 
**BUG**:  Drop down list does not open after clicking on its handler 

![image](https://user-images.githubusercontent.com/3728712/104449310-737ad680-55af-11eb-8bc3-f24e02f00487.png)

**Comment by alansemenov** [comment]
Has to be fixed in a different way
