### ISSUE TITLE
Use lib-common.sanitize()

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1716]
Class [NamePrettyfier](https://github.com/enonic/lib-admin-ui/blob/master/src/main/resources/assets/admin/common/js/NamePrettyfier.ts) (supposedly) duplicates [NamePrettyfier](https://github.com/enonic/xp/blob/master/modules/core/core-api/src/main/java/com/enonic/xp/name/NamePrettyfier.java) in XP and can (hopefully) be replaced by using [lib-common.sanitize](https://developer.enonic.com/docs/xp/stable/api/lib-common#sanitize).

**Comment by rymsha** [comment]
I don't think, it is possible.
lib-admin-ui does not depend on XP or its libraries and can't use anything from there.

BTW, some core apps do depend on lib-admin-ui so it will be problematic to build a proper distro if lib-admin-ui depends on XP anyhow.
