### ISSUE TITLE
Option Set - labels should be sanitized

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1751]
1. Open and add  html-area input in Option 3 in `optionset.xml`  (Features)
```
   <option name="option_3">
          <label>Option 3</label>
          <help-text>Help text for Option 3</help-text>
          <items>
            <input name="imageselector" type="ImageSelector">
              <label>Image selector</label>
              <indexed>true</indexed>
              <occurrences minimum="1" maximum="1"/>
              <config/>
            </input>
           <input name="htmlarea_text" type="HtmlArea">
             <label>HTML content 0:1</label>
             <occurrences minimum="0" maximum="1"/>
             <help-text>HTML Area</help-text>
           </input>
          </items>
````
2. Redeploy the app and open OptionSet wizard
3. Fill in the content-name input then click on Option 3 in `Multi selection`

![image](https://user-images.githubusercontent.com/3728712/105495569-622b7b80-5ccd-11eb-80a7-245f1076b495.png)

4. Insert a table  in html-area and save the content.

**BUG**- sources of html-table displayed  as label for Item Set

![image](https://user-images.githubusercontent.com/3728712/105496592-bd11a280-5cce-11eb-8ba8-9c1296842478.png)

**Collapsed** `Multi selection` 

![image](https://user-images.githubusercontent.com/3728712/105496950-3ad5ae00-5ccf-11eb-8278-2aae47fcd784.png)

**Comment by alansemenov** [comment]
@ashklianko can you verify that this has been fixed with your latest changes?

**Comment by ashklianko** [comment]
Ok

**Comment by ashklianko** [comment]
Problem is in directly setting `nodeValue` out of our Element api that escapes HTML, however escaping won't be enough since we don't want anyway plain htmlarea source with tags and other and need to transform it as we do for TextComponent name
