### ISSUE TITLE
Incorrect highlighting of required item/option-set occurrence

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1789]
Single-select:
1. Move the asterisk marking the mandatory option-set up to the option-set's title (you don't see it anyway until you have selected an option)

![image](https://user-images.githubusercontent.com/11612490/107393051-9f2fa480-6afa-11eb-872d-994c729bf569.png)

Here (above) you don't see that the "Single selection" option-set is required (minimum=1) until you have selected an option, then you see the asterisk: 

![image](https://user-images.githubusercontent.com/11612490/107393216-d43bf700-6afa-11eb-89f9-b982b93c960a.png)

Multi-select option-set (and item-set):
1. Hide the title when no options are selected
2. Move the asterisk marking the mandatory option-set up to the option-set's title

![image](https://user-images.githubusercontent.com/11612490/107392559-1b75b800-6afa-11eb-957e-40f106ed5b38.png)

**Comment by pmi** [comment]
@alansemenov
We will not be able to expand/collapse occurrence If we hide occurrence label when no options are selected
