### ISSUE TITLE
Subtitle in multi-select Option Set is not correctly generated

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1811]
**Case 1**
1. Open Option Set wizard
2. Click on `Option 1` then on ` Option 3`
3. Type a text in the HtmlArea in `Option 3`

![image](https://user-images.githubusercontent.com/3728712/108497235-35fb1e80-72bc-11eb-9779-39ffe4dcdca6.png)

**BUG**: subheader is not displayed, expected - `test` should be in the subheader

4. Unselect `Option 1` and `Option 2`
 Subheader gets visible: 

![image](https://user-images.githubusercontent.com/3728712/108497476-8d00f380-72bc-11eb-93d0-09a3b7f80b09.png)

**Case 2**  - Insert HtmlArea in  `Option 2` 
1. Open Option Set wizard
2. Click on `Option 3`
3. Insert a text in Option 2 then Option 3 
**BUG** -  text from the Option 3 is not displayed in the subheader

![image](https://user-images.githubusercontent.com/3728712/108497893-2d571800-72bd-11eb-8f1d-203fe261a7e7.png)

**Comment by alansemenov** [comment]
Case 2 is invalid because we always fetch value from the first non-empty input
