### ISSUE TITLE
Possibility to change default dropdown-behaviour for radio-typed option-sets

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-admin-ui#1812]
Our editors are struggeling with how options-sets using the radio-styled "only one option allowed" setup turned out in CS3.2. It went from an UX-friendly and easy to overview display of 2-4 radiobuttons, into a more inconvenient to use dropdown (that you must locate and click the [...]-menu and select "Reset" to be able to change a selection). There's no option/config to use good old radio buttons either (dropdowns already comes with bad UX, even more so when it contains few items).

The main problem for us was we relied on a data design were we had option-sets with pre-selected default values. They started out as something, but the editors could easily change that to something else. Like "select type of image" which pre-selected "photo" option displaying an ImageSelector populated from the folder/path photos , but you could change to option "illustration" displaying some other fields and a selector populated by the illustration path.

Could this be selectable somehow for the developer? An option on the option-set, or similar.

I'm not alien to the idea that we're using the option sets in a way not meant to be. We wanted more dynamic forms, easy to use with most options pre-selected for the editor but easy to adjust to less common options.

**Comment by sigdestad** [comment]
Maybe you could share what your current form looks like?

**Comment by Bellfalasch** [comment]
So this custom image selector for instance uses an `option-set` where you have three choices, but we always start by selecting `none` for you as a default choice.

<img width="549" alt="Skjermbilde 2021-02-22 kl  14 25 23" src="https://user-images.githubusercontent.com/1465598/108714561-fd588080-7519-11eb-964a-68bc23bdc67a.png">
<img width="559" alt="Skjermbilde 2021-02-22 kl  14 25 36" src="https://user-images.githubusercontent.com/1465598/108714566-fdf11700-7519-11eb-8beb-c3c705fcb0e9.png">

We could allow for no selection at all instead of the option none, it would require some rewriting in our controllers but not that big. Thing was that our code became simpler if we could expect an option, and also the editors prefered it being more of an active choice to actually select "none" to deactivate an image (if needed).

**Comment by sigdestad** [comment]
"None" is indeed an antipattern. I suggest you change this to just the two remaining options, and set min-occurence=0.

**Comment by sigdestad** [comment]
Also, is max-occurence =1?

**Comment by sigdestad** [comment]
Still, desire to have a radio-visualisation is a valid requirement, maybe this makes sense for single-select, single-occurance mode?

**Comment by Bellfalasch** [comment]
Yeah, I can see that the automatic "none" is not optimal, however the editors really liked that this felt more like an active choice to select "none" than to select nothing / leave it as it is. In the beginning, Illustration was our main choice. We would then know that selecting "None" was an active choice made, not something missed by accident. However this later turned into the default choice, so now it might need a re-thinking. We could use an item-set, that is not expanded, that says "add image", and from there you select type, but since data structures are a bit troublesome to migrate we're trying hard not to change the data structure in the process.

`min-occ...` for this is currently 1, yes.

But yeah, if you are given a set of different choices, in only one occurance, those choices are easier to overview with radio buttons - all available options are easily to overview by just scrolling the form, even for already published items.

**Comment by Bellfalasch** [comment]
Til info: we have now removed the `minimum=1` and changed that to `minimum=0` and instead update all code to check for`_selected === null` instead of `_selected === 'none'`, which solves the pressing UX problems for us. It would still be nice with radio buttons over dropdowns, but we no longer need it. So, if it is just troublesome for you and you don't believe fully in the idea, feel free to just close it. I wouldn't mind to be able to control this, and I prefer radios over dropdowns, but as I said I no longer need this for my current setup.
