### ISSUE TITLE
TextLine with exceeded length doesn't affect validity of the content

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1816]
We have [max-length](https://developer.enonic.com/docs/xp/stable/cms/input-types#textline) config for TextLine input. If length of the input value exceeds allowed length, we invalidate the input but this doesn't affect validity of the content - it remains valid and can be saved. If the content is saved, the field will be cleared entirely.

Fix it so that a TextLine with exceeded length makes the content invalid and it's not possible to save it. 

![image](https://user-images.githubusercontent.com/11612490/109023257-ee5e0380-76bc-11eb-8f52-e1b7ee1430ec.png)

**Comment by ashklianko** [comment]
Same problem with number input types
