### ISSUE TITLE
Implement length counter for TextLine and TextArea

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#1817]
* Support a config property called `showCounter`

* When it's set to `true`, show the number of entered characters in `length-counter` div underneath the field (in regular black color): "_X characters_"
![image](https://user-images.githubusercontent.com/11612490/109026513-1dc23f80-76c0-11eb-911c-770d22038e07.png)

* When both `showCounter` and `max-length` are set, combine the two texts like this: "_X characters / Y remaining_" where X is value length and Y is what we now show in the countdown

* Note that "_X characters_" remains in black while "_Y remaining_" is either green or red, depending on whether `max-length` is exceeded or not. See also https://github.com/enonic/lib-admin-ui/issues/1819 for new changes of the countdown.

![image](https://user-images.githubusercontent.com/11612490/109127348-9bcd2780-774e-11eb-82b9-e9c7789e6640.png)

![image](https://user-images.githubusercontent.com/11612490/109126980-2feabf00-774e-11eb-9cbf-6cfc0e975699.png)

**Comment by sigdestad** [comment]
Can we change this to a countdown instead?

**Comment by alansemenov** [comment]
We already show the countdown when `max-length` config is used (see below). So if the goal was to have a countdown, not the counter, then there's nothing to do

https://user-images.githubusercontent.com/11612490/109058816-bd44f980-76e3-11eb-8c47-b3648981cdfe.mov

**Comment by sigdestad** [comment]
We'd like both a counter, and a countdown :-). 
Also not sure how countdown currently behaves related to exeeding limit, should show -x in red I guess? Countdown should probably show "xx remaining", and counter should say "xx characters"?

**Comment by sigdestad** [comment]
Like the green and red behaviour also 👍

**Comment by alansemenov** [comment]
Updated description and created a [separate task](https://github.com/enonic/lib-admin-ui/issues/1819) to change styling of the countdown.

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/lib-admin-ui/pull/1823
