### ISSUE TITLE
HTML Area - Focused image is not loaded into Insert image dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#195]
1. Open content with HTML Area
2. Insert a new image into the Area using the "Insert image" modal dialog. The image is inserted and has a focus.
3. Open the "Insert image" dialog again.

When the image is focused it's supposed to be loaded into the dialog so that user could update it, but it doesn't happen. 

![image](https://user-images.githubusercontent.com/11612490/33062786-ce1f9862-cea0-11e7-9dce-da0a37d54c35.png)

**Comment by sigdestad** [comment]
Also, there is something wrong with the layout, the image label should be above the input, not to the left.
