### ISSUE TITLE
TextLine input shouldn't be valid when value does not match regular expression

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#1965]
1. Select Features and open wizard for `Text Line with Regular expression` 
2. Insert not valid IP address
![image](https://user-images.githubusercontent.com/3728712/119993070-da83af80-bfd3-11eb-9821-2727345cc070.png)

BUG: 
1) content should be not valid when text Value does not match with regular expression
2) Publish menu should be disabled (Create Task should be the default action)
3) text input has green border, but the value is not valid
4) Click on Save button:  Warning message appears

![image](https://user-images.githubusercontent.com/3728712/119993745-95ac4880-bfd4-11eb-86c5-09590ec92563.png)

**Comment by ashklianko** [comment]
I agree only about input color with invalid user input - it should be red, however we don't save invalid input: corresponding data property keeps null instead of invalid value, and if input is not required then input itself is considered valid

**Comment by alansemenov** [comment]
Yes, we should absolutely fix the input color.
But another strange thing here is the warning that comes after save. Is that because we are trying to save "null" into a field that allows only values defined by a regex? Why do we save the null value at all?

**Comment by ashklianko** [comment]
Will check

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/lib-admin-ui/pull/1966
Also fixed error message issue
