### ISSUE TITLE
Refactor SelectedOptionsView and SelectedOptionView interfaces and their deriving classes

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#197]
Problem 1: Too much duplicate code related to "Edit" and "Remove" icons in selected options section - this should be centralized in the base classes.

Problem 2: "Edit" and "Remove" icons are hidden via CSS - they should not be in DOM if they are not supposed to be shown, it's too easy to make them visible by tweaking CSS via dev tools.

**Comment by sigdestad** [comment]
Nice, would it be "safer" to use the interface if we placed the pencil at top left instead of next to the x? Remember it needs to work on touch too..
