### ISSUE TITLE
New Issue Dialog - Item list overlaps options in the  Items-combobox

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#243]
1. Select a content and open New Issue dialog
2. Add 4-7 items 
3. Scroll the dialog and click on the drop-down handler in the items-comboBox 

Bug: option list hidden by the selected options.
![issue2](https://user-images.githubusercontent.com/3728712/33824848-be038134-de70-11e7-9f06-d354cb2c61e8.png)

**Comment by alansemenov** [comment]
There's a similar issue with item list overlapping assignees dropdown, mentioned in https://github.com/enonic/xp-apps/issues/352

**Comment by pmi** [comment]
Right, should be fixed by #352
