### ISSUE TITLE
Users App - trim spaces in displayName input (Wizards)

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#254]
@sgauruseu commented on [Wed Oct 25 2017](https://github.com/enonic/xp-apps/issues/184)

1. Open a user-wizard or role-wizard, type a data and type a display name with spaces
2. Save the item, go to the grid
Bug: display-name was saved with spaces. 

![space](https://user-images.githubusercontent.com/3728712/31992299-9b5bcb40-b982-11e7-9d68-e7b9fbb50252.png)

**Comment by sigdestad** [comment]
This trimming definetly needs to happen in the API too. Any value with excessive whitespace before or after needs to be removed.

**Comment by edloidas** [comment]
@sigdestad Pushed a [commit](https://github.com/enonic/xp-apps/commit/d92f94d69cea596b671c8646bc68aaa35444a54a) to `xp-apps` since those changes must be done in server-side JS layer (`resources/lib/`).

**Comment by sigdestad** [comment]
Should'nt this be handled in the Java layer?

**Comment by edloidas** [comment]
Be it `app-contentstudio` or `app-applications`, sure. But we've moved some of the GraphQL, Elastic and common server operations to JS layer in `xp-apps/app-users`.

**Comment by sigdestad** [comment]
? But the graphQL stuff is just a proxy for the Java API's?

**Comment by sigdestad** [comment]
We should not have any core API's that are not available through Java...

**Comment by edloidas** [comment]
Well, yes, it's just a proxy. Actually, I wasn't talking about the core API.
Since we decided to use GrapQL for `app-users`, we've implemented users-specific schemas and query builders in the `app-users` itself, because we not needed that sort of code in the `xp`.
`app-users` is still using the authLib from the `xp`, that calls `Java` handlers and provides all basic operations (like creating user stores, updating groups, receiving authentification information). What we actually do in that JS layer in `app-users` is: validating GraphQL queries and calling Java code to execute them, building Elastic queries, creating valid objects for `xp` GraphQL lib, __AND validating and prettifying parameters, received from the client side.__

**Comment by sigdestad** [comment]
I fully understand this, my point was only that maybe the core Auth API should also trim away whitespaces from display names? As this clearly is not the case now, and it would solve problems regardless of the actual client inputting display names in the future :-)

**Comment by edloidas** [comment]
We have a small discussion here with Misnk guys. And my answer may be: "Maybe. Or maybe not.".
It's not just something that simple. For example, we have:

--app part--

__Server JS__
We have GraphQL and common validation here, that will won't be moved elsewhere. We may pass some params further, but some values must be validated here, like `key`, that is received from the client, but not passed to the handlers and only used to receive some other data to be passed. _We are currently trim, prettify and validate all data here. Sometimes, twice (`required` check): in functions and in GraphQL schemas._ 

_--xp part--_

__auth.js__
We check required params here (check for null), but nothing more. It's just a proxy. On the other hand, we are using `auth-lib` everywhere, not only in `app-users`. Some customers may use it. And we don't have good validation. :(

__Java Handlers__
Called from the `auth-lib`. Don't think we should check anything here. We must have __predictable__ behavior. Maybe we should add/improve `auth.js` checks, validation, and prettification of the params?

**Comment by alansemenov** [comment]
@edloidas Please don't overcomplicate this again. Just find the server-side code that handles create and update operations for principals and add trimming there (in addition to what I wrote earlier about the authlib code). It's not about checking or validation, it's about trimming the string values before we save them, simple as that.

**Comment by edloidas** [comment]
@alansemenov Do you mean Java or JS server-side? If it's all about JS and that [Pull Request](https://github.com/enonic/xp-apps/pull/365), then I've already updated it, according to demands in [commit](https://github.com/enonic/xp-apps/pull/365/commits/7c8f685fc36c12a296628349650180f3f39e2c43).
Or, are you talking about the Java handlers?

**Comment by alansemenov** [comment]
Java handlers.

Your changes to PR look fine now.
