### ISSUE TITLE
Can't set selected value in DropdownTreeGrid

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#2574]
1. Open a wizard with html area, insert an image
2. Do a double click on the insereted image.

**BUG**  - Image selector is present in Update Image dialog

![image](https://user-images.githubusercontent.com/3728712/169648865-057d727b-125b-4f60-8fcb-740919cf7437.png)

3. Click on `Update` button - dialog does not close

![image](https://user-images.githubusercontent.com/3728712/169648917-59aefe6a-231a-4b37-a136-860f84a1e4a9.png)

**Comment by alansemenov** [comment]
Regression after https://github.com/enonic/lib-admin-ui/issues/2563
