### ISSUE TITLE
Help text and counter overlap for TextLine input

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#2594]
When a TextLine input has both `help-text` and `config.showCounter`, then help text and counter will overlap:
![image](https://user-images.githubusercontent.com/11612490/170132679-05ab09ff-64fc-4245-8e36-d71f594d3db0.png)

Solution is to apply right padding to the help-text div when it's preceded by an input with both `text-input-type` and `show-counter` styles applied. Also check if we have the same issue with TextArea.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/11612490/170136203-41b3d642-73bb-4377-a687-fdd623564fee.png">

**Comment by jsi** [comment]
This bug is fixed for `show-counter`, but not for `max-length`.  We need a fix for max length as well.  See discussion with Tom Arild on Slack today (comments on my announcement of the release).

**Comment by reisfmb** [comment]
@jsi Thank you. Will fix it today

https://github.com/enonic/lib-admin-ui/issues/2598
