### ISSUE TITLE
InputTypeView: add 'clean' method

### ISSUE THREAD

**Issue by ashklianko** [enonic/lib-admin-ui#2822]
Now we have `reset` button that is intended for re-setting values, however we also need a clean , for example for cleaning up dialog form on open

**Comment by ashklianko** [comment]
Need to reconsider using of a clean method that is currently implemented for the option sets and removes unwanted items from 'selected' array.

**Comment by alansemenov** [comment]
Done in https://github.com/enonic/lib-admin-ui/issues/2869
