### ISSUE TITLE
Title is not updated in Item Set occurences view

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#2879]
1. Select `Features` an open new wizard for `FormItemSet Minimum Occurrences`
2.  Fill in text inputs  in all `Label` inputs

**BUG** - Titles are not updated in occurrences of inputs

![image](https://user-images.githubusercontent.com/3728712/203078203-e55a5d13-b789-4515-b36a-ac181485667c.png)

**Comment by alansemenov** [comment]
Regression after https://github.com/enonic/lib-admin-ui/issues/2873
