### ISSUE TITLE
Optimize build time

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#2920]
Update the build scripts.

**Comment by edloidas** [comment]
Using `--cache` for ESLint decreases linting time:
| Type | Time |
| -- | -- |
| No cache | ~14.5s |
| Cache w/o changes | ~2.2s |
| Cache w/ changes | ~4.75s |

On Windows, command execution time can be measured with `Measure-Command { npm run lint:quiet }`

**Comment by edloidas** [comment]
Another step to optimize the build is to use `swc` to generate JS during dev build.
`swc` doesn't care about types, so in case of typescript we must check types separately. It can be done with `--noEmit` flag to make it a little bit faster, or with a full types generation. Because of the flags like `--skipLibCheck` usage, we might not be 100% the types are correct, so I suggest that we use a regular `tsc` for types generation in production mode, that will run on CI.

| Type | Time |
| -- | -- |
| `tsc` dev | ~15.1s |
| `tsc` prod | ~14.7s |
| `swc` + `tsc` types | ~10s |
| `swc` + `tsc` typecheck, `--noEmit` | ~9.5s |

**Comment by edloidas** [comment]
Dropping the support of the ES5 also adds some minor improvement (that is not actually visible, because `swc` is fast enough). But, what is more importantly the resulted non-minified JS becomes smaller ~20%.

**Comment by edloidas** [comment]
Migrating to ES6 must be done in a separate task, as it appears, that:
* Apps, that are using `lib-admin-ui` `lib` part must also be compiled into ES6, otherwise it will lead to:
  `Class constructor cannot be invoked without new` exceptions
* Some `lib-admin-ui` libraries, like `slickgrid`, rely on ES5 and can not be used with ES6+, e.g. [function regex](https://github.com/enonic/lib-admin-ui/blob/master/src/main/resources/assets/admin/common/lib/slickgrid/slick.dataview.js#L682)  does not support arrow functions, there.

**Comment by edloidas** [comment]
Enforcing rules of Enonic's ESLint [config](https://github.com/enonic/enonic-npm-modules/tree/master/packages/eslint-config) will make typecheck faster simply by making developers to avoid implicit `any`, function's implicit return types, and other things, that make compiler to do it itself on each compilation.

**Comment by edloidas** [comment]
The main issue we have now with compiling with `swc` is that some working code, that was compiled with `tsc` will throw error. It happens, when a class, that extends another class does not always call the `super()`, which will lead to `_this` variable remain `undefined`. `tsc` will forcefully assign it to `this`: `var _this = this;` at the beggining of the function.
It can be easily fixed, and found by the ESLint rule (not part of our config yet): `'constructor-super': ['error']`

**Comment by edloidas** [comment]
It's hard to measure the exact execution time for the Gradle build, it it may drastically change between the runs, so the numbers are true as an average value. The build were done where `nodeInstall` and `npmInstall` are already UP-TO-DATE, since they may add up to one minute to the build time:
| Type | Time |
| -- | -- |
| Old build | ~43s |
| New build | ~22s |

**Comment by edloidas** [comment]
Another improvement that can be made is to replace less with sass/scss or any other compiler that is distributed as binary file and works faster. It may give up to 5s build time improvement.

**Comment by ComLock** [comment]
FYI: My current "best" setup for nashorn is:

1. bundle ES5&6/TS using esbuild
2. concat in a polyfill for Object.getOwnPropertyDescriptors (because the esbuild wrapper uses it)
3. transpile the bundles to commonjs using swc

Due to /lib/cache, etc, one has to think about how many bundles to create, perhaps one per file, but that's a lot of wrapper code added...

**Comment by ComLock** [comment]
So I can see that 7.10.2 is running on OpenJDK 64-Bit Server VM 11.0.15 (GraalVM Community).
But that doesn't mean Graal-JS, right, so then does nashorn run inside graalvm?

**Comment by ComLock** [comment]
Funny, tsup does the same
https://tsup.egoist.dev/#es5-support

**Comment by edloidas** [comment]
Nice one, @ComLock. Does it really work faster instead of transpiling into the with `swc` to ES5 directly? Or are there some limitations?
Though  such setup is not applicable for lib-admin-ui for obvious reasons, it would be nice to have this setup for our vanilla/webpack starter.
No, "GraalVM Community" is just an indication, that Oracle now supports the GraalVM and tries to integrate it with JVM. It doesn't mean that we are now able to use Graal-JS for XP.

**Comment by ComLock** [comment]
I think tsup is just a "wrapper" around the other tools, to make things easy to configure. So I don't think it makes anything faster compile time, just less hazzle configuring.
