### ISSUE TITLE
Add some space below text input in item-set 

### ISSUE THREAD

**Issue by RF0** [enonic/lib-admin-ui#296]
When using an item-set, there is no space below the last input in the set, and it makes it look a bit "buggy". See attached screenshot.

<img width="427" alt="screen shot 2018-01-12 at 09 41 15" src="https://user-images.githubusercontent.com/951293/34866449-e0ee8a98-f77c-11e7-9687-22a66d1c810a.png">

**Comment by sigdestad** [comment]
Is this 6.13? There is definetly also something wrong with the headings there!

**Comment by alansemenov** [comment]
@RF0 what version of XP are you on? Below is a screenshot from 6.13.1, seems fine to me:

![image](https://user-images.githubusercontent.com/11612490/34941365-b6090640-f9f3-11e7-93e0-60fa16fe2ad4.png)

**Comment by sigdestad** [comment]
I saw a similar problem yesterday, the user had Firefox.
@RF0 any comment?
