### ISSUE TITLE
Migrate to SlickGrid dependency from NPM

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#3112]
lib-admin-ui bundles SlickGrid as [NPM dependency](https://github.com/enonic/lib-admin-ui/blob/master/package.json#L33) but is in fact not using it. Instead, it [imports](https://github.com/enonic/lib-admin-ui/blob/master/src/main/resources/assets/admin/common/js/lib.ts#L3-L11) [locally bundled](https://github.com/enonic/lib-admin-ui/tree/master/src/main/resources/assets/admin/common/lib/slickgrid) version 2.4 of SlickGrid that is 7 years old.

It should be fairly simply to migrate (change imports in `lib.ts` to import directly from `node_modules`) but the biggest challenge here is that we tweaked `slick.grid.js` to support "gallery mode" in the Image Selector.

Migrating to the latest version might also help to ditch one of the "loose" rules of CSP that we now have to support because of SlickGrid.

**Comment by alansemenov** [comment]
We (may) have to implement a new control for Gallery mode of Image Selector's dropdown. This will help us ditch the custom changes we made in the SlickGrid library.

**Comment by ashklianko** [comment]
Depends on https://github.com/enonic/lib-admin-ui/issues/3193

**Comment by alansemenov** [comment]
No longer relevant
