### ISSUE TITLE
Duplicate of a read-only content item is not marked as read-only in the Content Grid

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#326]
When a read-only content item is duplicated, the copy gets the same permissions as the original item, but it won't be marked as read-only in the grid. You have to reload the grid for the copy to get marked as read-only.

**Comment by sigdestad** [comment]
What is a "read only" content item???

**Comment by alansemenov** [comment]
An item that current user has read-only access to and that looks "disabled" in the grid.

http://xp.readthedocs.io/en/stable/admin/contentstudio/content-tree.html?highlight=only%20read

> If current user has only read access to a content item, such item will be slightly dimmed in the grid.
