### ISSUE TITLE
Restore help text icon for non AI inputs 

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#3716]
Disable icon only for the inputs, that are editable by AI.

**Comment by sigdestad** [comment]
We don't really want to do this - We drop the help icon all over the place. It will be confusing if one field has AI, and another has the help text on the same location.

**Comment by alansemenov** [comment]
@sigdestad the idea was not to combine, but keep the help icons for all inputs if AI Content Operator app is not installed.

**Comment by edloidas** [comment]
The problem occurred when we added help text to the site settings (site.xml) just to find out that all icons are gone now.
