### ISSUE TITLE
Remove jQuery simulate plugin

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#3746]
It's pretty easy to simulate Mouse Click with native tools. Since jQuery's simulate is only used it few places, it can be esily removed.
Example:
```ts
// Step 1: Select the element
const element = document.getElementById('myButton');

// Step 2: Create the click event
const clickEvent = new MouseEvent('click', {
    bubbles: true,
    cancelable: true
});

// Step 3: Dispatch the click event on the element
element.dispatchEvent(clickEvent);
```

**Comment by alansemenov** [comment]
I've actually started it here: https://github.com/enonic/lib-admin-ui/blob/fcca461eacab719955b3077e007c9948df1c5a5d/src/main/resources/assets/admin/common/js/dom/ElementHelper.ts#L248-L255. Now it's as simple as doing `myElement.dispatchEvent('click')`
