### ISSUE TITLE
Incorrect styles in selectable ListBox

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#3749]
1. Open wizard for new content-selector (tree mode) 
2. Select a content in the root directory

**BUG**  - Incorrect styles in ListBox

![image](https://github.com/user-attachments/assets/ab4ab625-302f-4984-84fa-9a0d60c419ec)

**Comment by ashklianko** [comment]
Pushed into https://github.com/enonic/lib-admin-ui/pull/3748
