### ISSUE TITLE
Implement lazy rendering of UI controls

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#378]
When Content Wizard contains a lot of image selector controls the page slows down proportionally to the number of controls. One of the reasons is that each image selector makes an API request to fetch data for the images selected in that selector.
What we should do is make one request to fetch data for ALL of the images and render all of them once the data is fetched.

This problem was [reported](https://enonic.zendesk.com/agent/tickets/2347) by Norsk Topfotball who have 141 item sets on the page, each with an image selector. The page is making 141*2=282 requests, first to select the option in the selector and second to render select image under the selector. The page is loading for 2 minutes and then dies.

**Comment by sigdestad** [comment]
UPS! We can definetly _not_ to a single request to render 200+ images. This could have dramatic side-effects. We need to discuss this before anything is concluded..

Imho best solution here is simply to lazy load the image _when_ it is visible for the user, just like newspapers etc do now when you scroll down their pages.

**Comment by alansemenov** [comment]
dramatic effects? it takes exactly the same time to fetch info for 200 images as it does to fetch one. we do need to implement lazy rendering, but that's another issue. when the image is scrolled into the view, the data should already be available on the client.
