### ISSUE TITLE
Unneeded scrollbar appears on the modal dialog, when combobox is expanded

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#385]
1. Open Issue Details Dialog, click on items
2. Click on the drop-down handle and expand the items-combobox

Issue: **Unneeded scrollbar** appears  on the dialog

<img width="564" alt="modal" src="https://user-images.githubusercontent.com/3728712/36968891-e933210c-2074-11e8-8a8f-cc2f8eac804f.png">

**Comment by alansemenov** [comment]
Fixed in https://github.com/enonic/lib-admin-ui/issues/405
