### ISSUE TITLE
Create a new media content when an image is dragged into the CKEditor

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#443]
In CKEditor it's possible to add an image to the editor by simply dragging it into the area - very useful. However, in that case we should create the image as an attachment to be able to reference it (just like we do now when using the Upload button in the Insert Image dialog)

**Comment by sigdestad** [comment]
Important comment on this, we should not create an attachment, but a new media (just like we do when you drag an image on the imageSelector)
