### ISSUE TITLE
Edge specific bug - incorrect label in attachment-content and 404 Error, when click on it

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#449]
1. Open CS in `Edge`
2. Select `Features`, click on `New`, select `Attachments`
3. Upload an  attachment 
**Bug**: path to the local resource is displayed

![att](https://user-images.githubusercontent.com/3728712/39048035-ce5cb736-44a4-11e8-9fd8-19215f77c31c.png)

4.  type name and Save the content
5. Click on the attachment-link
**BUG**:  404 Error appears in the browser 
![404](https://user-images.githubusercontent.com/3728712/39048078-ed129222-44a4-11e8-9800-2993c8e391aa.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/xp #6324](https://github.com/enonic/xp/issues/6324) via [**ZenHub**](https://www.zenhub.com/)
