### ISSUE TITLE
 PageComponentView - Incorrect behavior, when double clicking on Text-component menu item.

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#480]
1. Open `Features`, open PageComponentView and click on `Customize`
2. Double click on  'Hello world' item in PageComponentView 

**Bug**: 
1) when editor  is CKE - double click on the menu-item removes  the text from component

![feat](https://user-images.githubusercontent.com/3728712/39698907-74d45df0-51ff-11e8-8b00-7510d15ec974.png)

2) Editor does not open,  when do double click on the text component in the second time

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #88](https://github.com/enonic/app-contentstudio/issues/88) via [**ZenHub**](https://www.zenhub.com/)
