### ISSUE TITLE
Publish Button in the Content Wizard doesn't switch to docked version on mobile resolution

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#484]
We now treat 720px as a threshold between mobile and desktop versions.

In the Content Grid we switch the Publish Button to compact version (square green button with no caption) under resolution <= 720px. 

In the Content Wizard nothing happens on 720px, but on 540px the button switches to the version docked to the bottom. It should happen earlier, on 720px.

**Comment by pmi** [comment]
Issue moved to [enonic/app-contentstudio #102](https://github.com/enonic/app-contentstudio/issues/102) via [**ZenHub**](https://www.zenhub.com/)
