### ISSUE TITLE
Item should not be unselected in a grid when new changes were saved in wizard 

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#538]
1. Open Users(CS) type a user name in Filter Panel
2. Click on the row with the filtered user and click on Edit button
![image](https://user-images.githubusercontent.com/3728712/40535283-4fd139d6-6011-11e8-9dfe-9ba75a326e14.png)

3. Do some changes in the wizard , save all and close the wizard(or go to the grid)
  
![image](https://user-images.githubusercontent.com/3728712/40535329-775e75e0-6011-11e8-8da3-f69b349c679d.png)

**Comment by vbradnitski** [comment]
fixed in #541
