### ISSUE TITLE
Details panel is empty - when content is selected and Show Details button has been pressed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#540]
1. Browser window should be maximized
2. Select a content
3. Open `details panel`

Bug: details panel is empty.
This bug can be linked with the   lib-admin-ui/issues/537

![image](https://user-images.githubusercontent.com/3728712/40583399-a0bb3da2-6196-11e8-93e7-81e3443bd61d.png)

**Comment by vbradnitski** [comment]
fixed in #541
