### ISSUE TITLE
CKEditor: change fullscreen mode to open in modal dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#547]
* "Modal" mode is only for desktop mode. Should take the entire screen (like now) on mobile resolution
* (Only if it's easy to implement) In "modal" mode we don't need the bottom toolbar - the "Source" button should be in the top toolbar and the fullscreen mode will be closed with the "X" icon
 
![image](https://user-images.githubusercontent.com/11612490/40659966-07dcf9e8-6350-11e8-8e36-3d9a553d1266.png)

**Comment by ashklianko** [comment]
What about navigation bar in the bottom?

**Comment by alansemenov** [comment]
Good point - let's keep the bar and just hide the "close fullsreen" button with css. Should be simple.
