### ISSUE TITLE
Custom selector doesn't give error messages for incorrect response

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#636]
We used to give user an error message when response with custom selector options contained invalid JSON - for example, when some required fields were missing (case A) or option ids were not unique (case B) - but this doesn't seem to happen anymore. The dropdown says "Searching..." and nothing happens. As of now, it's very difficult to understand if you made a mistake when returning the list of options from the service.

This can be tested by removing "id" fields in JSON response in ``service\customSelector.js`` (case A) or changing both id values to the same value (case B)

**Comment by pmi** [comment]
Fixed in PR #642 for task #635
