### ISSUE TITLE
Grid selection gets lost when alignment of the checkbox column changes

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#65]
1. Open the Content Studio
2. Select a couple of items in the grid
3. Resize width of the browser window until the checkbox column switches to right-alignment

Selection is lost. We should keep the selection whenever the column alignment changes.

**Comment by pmi** [comment]
Issue moved to [enonic/xp-apps #88](https://github.com/enonic/xp-apps/issues/88) via [**ZenHub**](https://www.zenhub.com/)
