### ISSUE TITLE
CKE: Internal CKE elements are visible in preview

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#660]
**Case 1:**
1. Open Features for editing
2. Add text component to the page
3. Open the Insert Image dialog, select an existing image, clear the Caption and Alt fields
4. Insert the image
5. Save 
6. Open preview

Image drag handler is visible under the image.

![image](https://user-images.githubusercontent.com/11612490/42087936-073983b6-7b98-11e8-9299-0d7096d93dd5.png)

**Case 2:**
1. Same as above, but after 5 click the image inside the editor and delete it.

The image is deleted but text "image widget" appears where the image used to be. Not sure where it's coming from because there's nothing in the source dialog. The text will disappear after save but it shouldn't be visible in the first place.

![image](https://user-images.githubusercontent.com/11612490/42123161-50c0d452-7c4d-11e8-8afe-24d2dbecda74.png)

![image](https://user-images.githubusercontent.com/11612490/42123177-96e99ec8-7c4d-11e8-82d1-90c0b8f28c0c.png)

**Comment by ashklianko** [comment]
I'll move second part to separate issue

**Comment by alansemenov** [comment]
fixed in another task
