### ISSUE TITLE
CKE: Cmd+K won't open Insert Link dialog

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#664]
Cmd+K used to open the Insert Link dialog in TinyMCE, but it doesn't work in CKE

**Comment by ashklianko** [comment]
Possibly mac issue, works on my local;

**Comment by alansemenov** [comment]
My bad - it's caused by incorrect handling of anchor list on production server, fixed by https://github.com/enonic/lib-admin-ui/issues/654
