### ISSUE TITLE
CKE: Image with justify alignment is not 100% wide

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#666]
See the screenshot below: CKE is on the left, Tiny is on the right. In Tiny justified image takes up the entire width, in CKE it doesn't. The reason is that ``img`` element in CKE has ``max-width: 100%`` instead of ``width: 100%``.

Hopefully this will be automatically fixed when we'll change the styles back to how they were (https://github.com/enonic/lib-admin-ui/issues/665)

![image](https://user-images.githubusercontent.com/11612490/42229178-20d9953a-7ee6-11e8-98bd-dd5e6e10cf8e.png)

**Comment by ashklianko** [comment]
Fixed in #665
