### ISSUE TITLE
Incorrect behavior of selection in grid - last selected item should be displayed in the preview panel

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#739]
This bug is  reproduced  when you select more than 10 previewable contents.
1. Click on checkbox and select 10  items in the grid (site or image)
2. Click on one more checkbox
BUG : 11th item should be displayed in the preview-panel
Actual - 10th item is displayed

![image](https://user-images.githubusercontent.com/3728712/43634949-42b0f20a-9716-11e8-89fd-0eaab04f7621.png)

The similar issue, when you select more than 10 items in the grid and then unselect the last item
Site is unselected, but it still present in the preview panel.

![image](https://user-images.githubusercontent.com/3728712/43634638-563b1fb8-9715-11e8-85c9-14b9e5f63fb7.png)

**Comment by ashklianko** [comment]
We have a restriction to 10 items for preview: 
PreviewContentHandler.BLOCK_COUNT is set to 10

@alansemenov do we need to update it?

**Comment by alansemenov** [comment]
This is not the same thing. The limit of 10 prevents opening more than 10 new tabs with content preview simultaneously. This has nothing to do with the preview panel.

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #362](https://github.com/enonic/app-contentstudio/issues/362) via [**ZenHub**](https://www.zenhub.com/)
