### ISSUE TITLE
Incorrect behaviour when trying to add link to an image 

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#749]
1. Select an image in the HTML Area
2. Click "Insert link" dialog

The bug here is that the dialog requires user to enter text but it shouldn't be required since we're adding a link to the image. In old TinyMCE we hid the "Text" input (and didn't validate it) in this case.

**Comment by ashklianko** [comment]
Will add PR to 6.15.1 in a moment
