### ISSUE TITLE
Browser console errors after drag'n'dropping a text component

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#769]
1. Open the Content Wizard for content that has a text component
2. Open Page Components view
3. Apply DnD to the text component

There will be console errors and the tree is now broken.

Same errors when dragging a text component directly inside the Page editor.

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #377](https://github.com/enonic/app-contentstudio/issues/377) via [**ZenHub**](https://www.zenhub.com/)
