### ISSUE TITLE
Double-click on link or macro inside HTML Area won't open modal dialog in inline mode

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#797]
Double-clicking a link or macro element inside HTML Area opens modal dialog for the clicked element, but only in the Wizard. In inline mode it doesn't work. However, it works fine for images and anchors.

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-contentstudio #410](https://github.com/enonic/app-contentstudio/issues/410) via [**ZenHub**](https://www.zenhub.com/)
