### ISSUE TITLE
Publishing dropdown and tree is hard to see, review the interface

### ISSUE THREAD

**Issue by RF0** [enonic/lib-admin-ui#798]
Publishing dropdown and tree is hard to see according to several users. Normally the dropdown arrow is to the right (i think?), but in Content Studio the dropdown is gray and to the left of the PUBLISH button, and it changes into a slighter black color when content is selected. This makes it hard to see if one do not know it is there. The tree in the publishing dialogue is also not obvious that is clickable. Perhaps this functionality should be user tested if it is not, to see if this is a problem for users. 6/8 course participants did not find out how to publish the entire tree, and two seasoned Xp veterans was also a bit gobsmacked of where it had gone.

<img width="294" alt="screen shot 2018-09-04 at 15 05 53" src="https://user-images.githubusercontent.com/951293/45033180-0d333000-b054-11e8-92f5-a567d14fc776.png">
<img width="182" alt="screen shot 2018-09-04 at 15 04 30" src="https://user-images.githubusercontent.com/951293/45033182-0d333000-b054-11e8-93af-3bbd28019831.png">

**Comment by sigdestad** [comment]
Agreed, we need to make this clearer!

**Comment by sigdestad** [comment]
Suggestions are:

* less space between text and "more"
* More like a button
* Move more to the right etc

**Comment by alansemenov** [comment]
This has been reworked for 7.0

**Comment by alansemenov** [comment]
This has been reworked for 7.0
