### ISSUE TITLE
Refactoring of modal dialogs

### ISSUE THREAD

**Issue by alansemenov** [enonic/lib-admin-ui#823]
1. Open Content Studio
2. Open "Create Content" modal dialog
3. Start pressing Tab button to change focused control.

At some point focus will leave the dialog and elements on the page start getting focus. It works correctly in other modal dialogs, like Delete, Move etc. In Publish dialog it doesn't look like any element gets focused at all.

Check all modal dialogs to make sure the behaviour is consistent everywhere.

**Comment by ashklianko** [comment]
List of dialogs with same problem (without html area dialogs):

- NewContentDialog
- ContentPublishDialog
- ContentUnpublishDialog
- IssueListDialog
- IssueDetailsDialog
- SchedulePublishDialog
