### ISSUE TITLE
The UI for the about dialog looks bad in IE11

### ISSUE THREAD

**Issue by RF0** [enonic/lib-admin-ui#84]
The Enonic Logo pushes out the content in the about dialog and it does not look nice. By removing the css height for the Enonic XP logo it looks normal. This is tested in windows 7, IE11 on crossbrowsertesting for 6.12.0-RC2. In Edge 15 the red XP logo does not show, but that looks ok.

.xp-about-dialog .xp-about-dialog-app-icon img {height: 135px}

<img width="881" alt="screen shot 2017-10-09 at 13 32 20" src="https://user-images.githubusercontent.com/951293/31336331-acf5e95a-acf6-11e7-81d9-e5472a4f6ae3.png">

<img width="351" alt="screen shot 2017-10-09 at 13 37 32" src="https://user-images.githubusercontent.com/951293/31336414-0d223efa-acf7-11e7-902a-39061a38bd71.png">

**Comment by ashklianko** [comment]
Issue moved to [enonic/xp-apps #123](https://github.com/enonic/xp-apps/issues/123) via [**ZenHub**](https://www.zenhub.com/)
