### ISSUE TITLE
Install App Dialog - first field doesn't get focus

### ISSUE THREAD

**Issue by sgauruseu** [enonic/lib-admin-ui#847]
This issue reproduce right after the login to XP
- Login to XP
- Go to Applications
- Click on `Install` button
- Modal dialog appears, press `Enter` key

Bug: Launcher Panel appears when `Enter` has been pressed

![image](https://user-images.githubusercontent.com/3728712/47014486-04557400-d153-11e8-9439-bf45caa1b2b2.png)

**Comment by ashklianko** [comment]
Issue moved to [enonic/app-applications #55](https://github.com/enonic/app-applications/issues/55) via [**ZenHub**](https://www.zenhub.com/)
